name: CI

on:
  push:
    branches:
    - main

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    - name: Run a script
      run: ".\Application Discovery Service\AWSDiscoveryAgentInstaller.ps1"
      shell: powershell